### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Yomguithereal** [robindemourat/clues-anomaly-understanding#1]
## Todo
- [x] Drop the strange `package.json~` file at project root.
- [x] Drop the strange `._.DS_Store` file in `app`.
- [x] Drop silly indexation file (example: `._1.png` in `app/data/images`).
- [x] Add `.DS_Store` to `.gitignore` (specially if you work on mac).
## Remarks

There seems to be quite a lot of `devDependencies` for your project. This is the price for using scaffolder though.
## Review items
- [Culprit](https://github.com/robindemourat/modulo/blob/master/app/views/modulo-aside-manager.html#L1-L9): Inconsistent indentation.
- Choose an ident number and stick to it across your js code. Sometimes you use 2 spaces, sometimes 4.
- Your `main.js` file is a good example of a file with both spaces and tab indentation. 'Tis no good, my liege.
- [Culprit](https://github.com/robindemourat/modulo/blob/master/app/scripts/controllers/main.js#L11): Refrain from using this dirty deps function args magic voodoo from Angular.
- [Culprit](https://github.com/robindemourat/modulo/blob/master/app/scripts/controllers/main.js#L66): line is difficult to read and understand. You should probably put the `wining` (did you mean `winning`?) in the line below.
- [Culprit](https://github.com/robindemourat/modulo/blob/master/app/scripts/controllers/main.js#L84): I am no Angular expert but I think this is evil.
- [Culprit](https://github.com/robindemourat/modulo/blob/master/app/scripts/controllers/main.js#L101): perilous construct.
## Possibilities

``` js
ok = view && view.role && view.role === 'modulo-view';
// into
ok = (view || {}).role === 'modulo-view';
```
